#Problem can be found here: https://projecteuler.net/problem=2
"""Verbatim: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
x = 0
li = [1, 2]

for item in range (1, 11):
	x = li[item] + li[item-1]
	li.append(x)
	print li
	